version: "3.8"

services:
  app:
    build:
      context: crawler
      dockerfile: Dockerfile
    environment:
      ENABLE_DEVTOOLS: "true"
    ports:
      - 5910:5910
    volumes:
      - type: bind
        source: ./data
        target: /data
    depends_on:
      mariadb:
        condition: service_healthy
    init: true
    restart: on-failure:5

  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootPassword
      MYSQL_USER: watcher
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: watch-twitter-likes
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-prootPassword",
        ]
      timeout: 20s
      interval: 5s
      retries: 30
    volumes:
      - "./db-data:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootPassword
      TZ: Asia/Tokyo
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - 8000:80
    volumes:
      - /sessions
