name: Auto add reviewer

on:
  pull_request_target:
    types:
      - opened
      - reopened
    branches:
      - main
      - master

jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    if: >-
      ${{
        github.actor != 'dependabot[bot]' &&
        github.actor != 'renovate[bot]' &&
        github.actor != 'github-actions[bot]' &&
        github.actor != 'book000'
      }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Add reviewer
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.pulls.requestReviewers({
              ...context.repo,
              pull_number: context.issue.number,
              reviewers: ["book000"]
            })
