# 任意のレジストリに複数の Docker image を公開orビルドする。
# master/mainのプッシュ時、プルリクの作成・更新時、リリース時に動作する。

name: Docker

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  job:
    name: Docker build (${{ fromJson(matrix.target).directory }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - '{ imageName: "ghcr.io/tomacheese/watch-twitter-likes", directory: "crawler" }'
          - '{ imageName: "ghcr.io/tomacheese/watch-twitter-likes-web", directory: "web" }'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ${{ env.REGISTRY }}
        if: github.event_name == 'release'
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: package.json update version
        if: github.event_name == 'release'
        working-directory: ${{ fromJson(matrix.target).directory }}
        run: |
          sed -r -i "1,/version/s/\"version\": \".+\"/\"version\": \"${{ github.event.release.tag_name }}\"/" package.json
          sed -r -i "s/\{\{VERSION\}\}/${{ github.event.release.tag_name }}/" web/public/sw.js

          git diff

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ fromJson(matrix.target).imageName }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: ${{ fromJson(matrix.target).directory }}
          push: ${{ github.event_name == 'release' }}
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
