# 任意のレジストリに Docker image を公開orビルドする。
# プルリクの作成・更新時に動作する。

name: Docker

on:
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - synchronize
    paths:
      - .github/workflows/docker.yml
  pull_request_target:
    branches:
      - main
      - master
    types:
      - opened
      - synchronize
      - reopened
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.merged == true && 'master' || github.event.pull_request.head.sha }}

jobs:
  docker-ci:
    name: Docker CI
    uses: book000/templates/.github/workflows/reusable-docker.yml@master
    with:
      targets: >-
        [
          { imageName: "tomacheese/watch-twitter-likes", context: "crawler", file: "crawler/Dockerfile", packageName: "watch-twitter-likes" },
          { imageName: "tomacheese/watch-twitter-likes-web", context: "web", file: "web/Dockerfile", packageName: "watch-twitter-likes-web" }
        ]
      platforms: linux/amd64
    secrets:
      DOCKER_USERNAME: ${{ github.actor }}
      DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
