name: hadolint

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  hadolint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: [crawler, web, mock-api]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ matrix.directory }}/Dockerfile
